(
src.process.imagePath 
	contains ("Signal.exe", "whatsapp.exe", "Telegram.exe", "WeChat.exe", "KakaoTalk.exe", "QQ.exe")
	OR 
	src.process.cmdline contains ("Signal", "whatsapp", "Telegram", "WeChat", "KakaoTalk", "tencent", "QQ")       
	OR tgtFile.path contains ("\\Signal\\", "\\WhatsApp\\", "\\Telegram Desktop\\", "\\Tencent\\WeChat\\", "\\Kakao\\KakaoTalk\\", "\\AppData\\Packages\\*WhatsAppDesktop*")
)