task.path contains 
  ('KMSpico','HEU_KMS_Activator','AutoPico.exe','KMSELDI','KMSAuto Net','microKMS','W10DigitalActivation','激活工具','激活软件') 
  or src.process.cmdline contains 
  ('KMSpico','HEU_KMS_Activator','AutoPico.exe','KMSELDI','KMSAuto Net','microKMS','W10DigitalActivation','激活工具','激活软件') 
  or tgt.process.cmdline contains ('KMSpico','HEU_KMS_Activator','AutoPico.exe','KMSELDI','KMSAuto Net','microKMS','W10DigitalActivation','激活工具','激活软件') 
  or src.process.image.sha256 in
(
  'be8278585dd62a3ce713dad8aa73f9dc60caa7b3ace652fe90d0d0fd505932d2',
  '28474e5c2646f95e3adc37f99af60c162ef0e18648e8eff886d1bb96e604afac',
  '622f1d0709bf283ebcf5fb36dd3ec6ae9c79c355917b153f428abf0bbc09b9e3',
  'bfc3db2e8d0bca6f4e189191d5500d6d6b5d9ce83c3ee379253cc20505fa24c3'
  )
