( tag="audit" action="launchQuery" queryGroupRequest.queries contains 'type":"PQ')  OR (tag="audit" action="launchQuery" queryGroupRequest.queries contains 'origin":"search') OR (tag="audit" action="launchQuery" queryGroupRequest.queries contains 'type":"PLOT' not(queryGroupRequest.queries contains 'origin":"SEARCH'))
status='success'

| parse "\"filter\":\"$filter$\"," from queryGroupRequest.queries
| columns user, filter, timestamp
| sort -timestamp
